import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.scss';
import Button from '@mui/material/Button';

const HomePage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Appinda Chronicles - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Button variant='contained' color='primary'>Hello</Button>
    </div>
  )
}

export default HomePage
