import { Fragment } from "react";
import type { NextPage } from "next";

import Head from "next/head";
import Box from "@mui/material/Box";
import Chip from "@mui/material/Chip";
import Paper from "@mui/material/Paper";
import FormGroup from "@mui/material/FormGroup";
import TextField from "@mui/material/TextField";
import Autocomplete from "@mui/material/Autocomplete";
import Typography from "@mui/material/Typography";
import Checkbox from "@mui/material/Checkbox";
import CheckBoxOutlineBlankIcon from '@mui/icons-material/CheckBoxOutlineBlank';
import CheckBoxIcon from '@mui/icons-material/CheckBox';

import ViewModuleIcon from "@mui/icons-material/ViewModule";
import ListIcon from "@mui/icons-material/List";
import SettingsIcon from "@mui/icons-material/Settings";

const icon = <CheckBoxOutlineBlankIcon fontSize="small" />;
const checkedIcon = <CheckBoxIcon fontSize="small" />;
const projectOptions = new Array(10).fill(1).map((_, i) => ({ title: 'Project ' + i, id: 'project' + i }));

const LogsPage: NextPage = () => {
  return (
    <Fragment>
      <Head>
        <title>Appinda Chronicles - Security</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box
        sx={{
          display: "grid",
          gridTemplateColumns: "200px auto",
          gridTemplateRows: "min-content auto",
          height: "100%",
        }}
      >
        <Paper
          square
          sx={{
            width: "100%",
            height: "100%",
            p: 1,
            gridRow: "1/3",
            zIndex: 2,
          }}
        >
          <Typography variant="h6">Filters</Typography>
          <br/>
          <p>hoi</p>
          <p>hoi</p>
          <p>hoi</p>
          <p>hoi</p>
          <p>hoi</p>
        </Paper>
        <Paper
          square
          sx={{
            height: "100%",
            width: "100%",
            p: 1,
            display: "flex",
            gap: 1,
            zIndex: 1,
          }}
        >
          <Chip label="Deletable" onDelete={() => {}} />
          <Chip label="Deletable" variant="outlined" onDelete={() => {}} />
        </Paper>
        <Box>
          <h1>hoi</h1>
        </Box>
      </Box>
    </Fragment>
  );
};

export default LogsPage;
