import type { NextPage } from 'next';
import Head from 'next/head';

const SettingsPage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Appinda Chronicles - Security</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Settings</h1>
    </div>
  )
}

export default SettingsPage
